import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';


export const metadata = {
    title: 'SignForge - Digital Signage Simplified',
    description: 'Generated by create next app',
  }

export default function Rootlayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider>
            <html>
                <head></head>
                <body>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    )
}